[General]
abstract = true
# General options in here

[InitSimpleConf]
network = SimpleNet
sim-time-limit = 100s

*.user[*].tasksPerSecond = 100
*.user[*].out.channel.datarate = 1Gbps
*.server.N_CORES = ${cores=1..16 step 1}
#*.user.out.channel.DynDelay = uniform(90ms,110ms)
#*.user.out.channel.DynDelay = ${d=exponential(100ms), uniform(90ms,110ms)}
#*.server.out.channel.DynDelay = ${d}

[MultiSimpleConf]
extends = InitSimpleConf
SimpleNet.N_USERS = ${users=1..5 step 1}
