[General]
abstract = true
# General options in here

[InitSimpleConf]
network = SimpleNet
sim-time-limit = 100s

*.user.out.channel.DynDelay = ${d=exponential(100ms), uniform(90ms,110ms)}
*.server.out.channel.DynDelay = ${d}