//
// Generated file, do not edit! Created by opp_msgtool 6.3 from L2multi.msg.
//

#ifndef __L2MULTI_M_H
#define __L2MULTI_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class L2multi;
/**
 * Class generated from <tt>L2multi.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet L2multi
 * {
 *     int source;
 *     int destination;
 *     bitLength = 64;
 * }
 * </pre>
 */
class L2multi : public ::omnetpp::cPacket
{
  protected:
    int source = 0;
    int destination = 0;

  private:
    void copy(const L2multi& other);

  protected:
    bool operator==(const L2multi&) = delete;

  public:
    L2multi(const char *name=nullptr, short kind=0);
    L2multi(const L2multi& other);
    virtual ~L2multi();
    L2multi& operator=(const L2multi& other);
    virtual L2multi *dup() const override {return new L2multi(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getDestination() const;
    virtual void setDestination(int destination);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const L2multi& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, L2multi& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline L2multi *fromAnyPtr(any_ptr ptr) { return check_and_cast<L2multi*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __L2MULTI_M_H

