//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simple.msg.
//

#ifndef __SIMPLE_M_H
#define __SIMPLE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Simple_task;
class Simple_result;
/**
 * Class generated from <tt>simple.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Simple_task
 * {
 *     int taskId;
 *     double complexityFactor;
 * }
 * </pre>
 */
class Simple_task : public ::omnetpp::cPacket
{
  protected:
    int taskId = 0;
    double complexityFactor = 0;

  private:
    void copy(const Simple_task& other);

  protected:
    bool operator==(const Simple_task&) = delete;

  public:
    Simple_task(const char *name=nullptr, short kind=0);
    Simple_task(const Simple_task& other);
    virtual ~Simple_task();
    Simple_task& operator=(const Simple_task& other);
    virtual Simple_task *dup() const override {return new Simple_task(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual double getComplexityFactor() const;
    virtual void setComplexityFactor(double complexityFactor);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Simple_task& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Simple_task& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>simple.msg:24</tt> by opp_msgtool.
 * <pre>
 * packet Simple_result
 * {
 *     int resultId;
 * }
 * </pre>
 */
class Simple_result : public ::omnetpp::cPacket
{
  protected:
    int resultId = 0;

  private:
    void copy(const Simple_result& other);

  protected:
    bool operator==(const Simple_result&) = delete;

  public:
    Simple_result(const char *name=nullptr, short kind=0);
    Simple_result(const Simple_result& other);
    virtual ~Simple_result();
    Simple_result& operator=(const Simple_result& other);
    virtual Simple_result *dup() const override {return new Simple_result(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getResultId() const;
    virtual void setResultId(int resultId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Simple_result& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Simple_result& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Simple_task *fromAnyPtr(any_ptr ptr) { return check_and_cast<Simple_task*>(ptr.get<cObject>()); }
template<> inline Simple_result *fromAnyPtr(any_ptr ptr) { return check_and_cast<Simple_result*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMPLE_M_H

